name: CI

"on":
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node ${{ matrix.node-version }} with corepack
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - name: Enable corepack (yarn v4)
        run: corepack enable
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build api
        run: cd api && yarn build:server
      - name: Test api
        run: cd api && yarn test 